CREATE TABLE links (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  link VARCHAR(255) NOT NULL,
  vpn_link VARCHAR(255),
  vpn_link_id VARCHAR(255),
  vpn_link_password VARCHAR(255),
  state VARCHAR(20) NOT NULL,
  time_end TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  time_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  time_update TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
