CREATE TABLE pay_link (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  pay_id VARCHAR(255) NOT NULL,
  amount INT NOT NULL,
  status VARCHAR(20) NOT NULL,
  date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  );

		
		